## An Activation Function decides whether a neuron should be activated or not. This means that it will decide whether the neuron's input to the network is important or not in the process of prediction using simpler mathematical operations.

#Activation Function


###Importing Libraries

In [12]:
import numpy
from numpy import array #For Array Initialization
from numpy import random #For Randomly choosing Numbers
from numpy import dot #For Doing DOT Product
from random import choice

###Initialized Dataset

In [13]:
dataset = [
    (array([0,0,1]), 0), #array([x,y,b],e) x,y=Input , b=bias, e=Expected O/P to validate
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]
print(dataset)
print(array([0,0,1]), 0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


###Initializing Random numbers for WEIGHTS

In [14]:
weights = random.rand(3)
weights

array([0.98481938, 0.84010774, 0.28679251])

###Initializing additional variables

In [15]:
r = 0.2 #learning Rate
n = 100 #Number of Iteration

##ACTIVATION FUNCTION

###Training & Evaluating using STEP Activation Function

In [16]:
activationFn = lambda x: 0 if x < 0 else 1 #step activation function (if i/p is negative o/p is 0 else 1)
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -0.113 ResultAFn: 0
ResultBAFn: 0.727 ResultAFn: 1
ResultBAFn: 0.872 ResultAFn: 1
ResultBAFn: 1.712 ResultAFn: 1


###Training & Evaluating using LINEAR Activation Function


In [17]:
activationFn = lambda x: x 

for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: 0.256 ResultAFn: 0.2558914685421048
ResultBAFn: 0.729 ResultAFn: 0.7285947139693758
ResultBAFn: 0.81 ResultAFn: 0.8096957248513672
ResultBAFn: 1.282 ResultAFn: 1.282398970278638


###Training & Evaluating using SIGMOID Activation Function

In [18]:
import numpy as np
activationFn = lambda x: 1/(1+np.exp(-x))
err = []
for j in range(n):
    x, expected = choice(dataset) 
    result = np.dot(weights, x) 
    error = expected - activationFn(result)
    err.append(error)  # Append the error to the list 'err'
    weights += r * error * x

for x, _ in dataset:
    result = np.dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))


ResultBAFn: -0.057 ResultAFn: 0.4858048535503802
ResultBAFn: 1.784 ResultAFn: 0.8562391212792926
ResultBAFn: 1.872 ResultAFn: 0.8667283222443579
ResultBAFn: 3.714 ResultAFn: 0.9761894988286159


###Training & Evaluating using RELU Activation Function

In [19]:
activationFn = lambda x: 0 if x < 0 else x 
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: 0.061 ResultAFn: 0.061113961620669795
ResultBAFn: 0.487 ResultAFn: 0.48662102582701505
ResultBAFn: 0.689 ResultAFn: 0.6885699961538307
ResultBAFn: 1.114 ResultAFn: 1.114077060360176


###Training & Evaluating using SOFTMAX Activation Function

In [21]:
# activationFn = lambda x: numpy.exp(x) / numpy.sum(numpy.exp(x), axis=0)
# err = []
# for j in range(n):
#     x, expected = choice(dataset) 
#     result = dot(weights, x) 
#     err = expected-activationFn(result)
#     error.append(err)
#     weights += r * err * x

# for x, _ in dataset:
#     result = dot(x, weights)
#     print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

In [22]:
import numpy as np
activationFn = lambda x: 1 / (1 + np.exp(-x))
err = []
for j in range(n):
    x, expected = choice(dataset)
    result = np.dot(weights, x)
    error = expected - activationFn(result)
    err.append(error)  # Append the error to the list 'err'
    weights += r * error * x

for x, _ in dataset:
    result = np.dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result, 3), activationFn(result)))


ResultBAFn: -0.161 ResultAFn: 0.4597181522202971
ResultBAFn: 1.669 ResultAFn: 0.8414623623512137
ResultBAFn: 1.902 ResultAFn: 0.8701201374481804
ResultBAFn: 3.733 ResultAFn: 0.9766298469538245
